version: '3'

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  mariadb:
    image: mariadb:10.3
    networks:
      - app
    command: --max-allowed-packet=64MB
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DATABASE: db

  db-backup:
    image: databack/mysql-backup
    networks:
      - app
    depends_on:
      - mariadb
    volumes:
      - /home/dkagms/bibbox-statistik-backup:/db
    environment:
      - DB_DUMP_TARGET=/db
      - DB_USER=db
      - DB_PASS=db
      - DB_SERVER=mariadb
      - DB_DUMP_BEGIN=+3

  phpfpm:
    image: matomo:3.14.1-fpm-alpine
    networks:
      - app
    depends_on:
      - mariadb
    volumes:
#      - ./config:/var/www/html/config:rw
#      - ./logs:/var/www/html/logs
      - matomo:/var/www/html


  nginx:
    image: nginx:alpine
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    # ports:
      # - 8080:80
    labels:  # used for Traefik dynamic configuration
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

volumes:
  db:
  matomo:
